#spring:
#  cloud:
#    config:
#      uri: http://localhost:8888
#  config:
#    import: "configserver:"
#  application:
#    name: auth-service-application

spring:
  cloud:
    config:
      uri: http://localhost:8888
  profiles:
    active: properties
  config:
    import: "optional:configserver:"
  application:
    name: auth-service-application